In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

In [3]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea


In [4]:
df.tail()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea


In [5]:
df.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder'],
      dtype='object')

In [6]:
df.shape

(374, 13)

In [7]:
df.dtypes

Person ID                    int64
Gender                      object
Age                          int64
Occupation                  object
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                object
Blood Pressure              object
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder              object
dtype: object

In [8]:
df.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000


In [9]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [10]:
df.fillna(0,inplace = True)

In [11]:
df.isnull().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

## Hot Encoding the Object datatypes GENDER, BMI CATEGORY

In [12]:
Gender_code = pd.get_dummies(df.Gender,dtype=int)
Gender_code.head(3)

,Female,Male
0,0,1
1,0,1
2,0,1


In [13]:
BMI_code = pd.get_dummies(df['BMI Category'] ,dtype=int)
BMI_code.head(3)

,Normal,Normal Weight,Obese,Overweight
0,0,0,0,1
1,1,0,0,0
2,1,0,0,0


In [14]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [15]:
df['BMI Category'] = df['BMI Category'].replace({'Normal Weight': 'Normal'})

In [16]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese'], dtype=object)

In [17]:
BMI_code = pd.get_dummies(df['BMI Category'] ,dtype=int)
BMI_code.head(3)

,Normal,Obese,Overweight
0,0,0,1
1,1,0,0
2,1,0,0


In [18]:
df.head(2)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0


In [19]:
df2 = pd.concat([df,Gender_code],axis='columns')
df2.head(3)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0,0,1
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1


In [20]:
df3 = pd.concat([df2,BMI_code],axis='columns')
df3.head(3)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0,0,1,0,0,1
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1,1,0,0
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1,1,0,0


In [21]:
df4 = df3.drop(['Gender','BMI Category', 'Occupation','Person ID'],axis='columns')
df4.head(3)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight
0,27,6.1,6,42,6,126/83,77,4200,0,0,1,0,0,1
1,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0
2,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0


In [22]:
df4[['Systolic', 'Diastolic']] = df4['Blood Pressure'].str.split('/', expand=True)
df4[['Systolic', 'Diastolic']] = df4[['Systolic', 'Diastolic']].apply(pd.to_numeric)
df4.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,27,6.1,6,42,6,126/83,77,4200,0,0,1,0,0,1,126,83
1,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0,125,80
2,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0,125,80
3,28,5.9,4,30,8,140/90,85,3000,Sleep Apnea,0,1,0,1,0,140,90
4,28,5.9,4,30,8,140/90,85,3000,Sleep Apnea,0,1,0,1,0,140,90


In [23]:
df5 = df4.drop('Blood Pressure',axis = 'columns')
df5.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,27,6.1,6,42,6,77,4200,0,0,1,0,0,1,126,83
1,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80
2,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80
3,28,5.9,4,30,8,85,3000,Sleep Apnea,0,1,0,1,0,140,90
4,28,5.9,4,30,8,85,3000,Sleep Apnea,0,1,0,1,0,140,90


In [24]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, ShuffleSplit
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [25]:
df5["Sleep Disorder_numeric"] = df["Sleep Disorder"].map({0:0,'Sleep Apnea':1, 'Insomnia':2})

In [26]:
df5['Sleep Disorder_numeric'].unique()

array([0, 1, 2], dtype=int64)

In [27]:
df5.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,27,6.1,6,42,6,77,4200,0,0,1,0,0,1,126,83,0
1,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80,0


In [28]:
df6 = df5.drop(['Sleep Disorder'], axis=1)
df6.head(3)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,27,6.1,6,42,6,77,4200,0,1,0,0,1,126,83,0
1,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80,0
2,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80,0


In [29]:
df6.to_excel("new_df.xlsx",index=False)

In [30]:
X = df6.drop(['Sleep Disorder_numeric'], axis=1)
y = df6['Sleep Disorder_numeric']

In [31]:
print(y.shape)
print(X.shape)

(374,)
(374, 14)


In [32]:
X.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,27,6.1,6,42,6,77,4200,0,1,0,0,1,126,83
1,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80
2,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80
3,28,5.9,4,30,8,85,3000,0,1,0,1,0,140,90
4,28,5.9,4,30,8,85,3000,0,1,0,1,0,140,90


In [33]:
y.head()

0    0
1    0
2    0
3    1
4    1
Name: Sleep Disorder_numeric, dtype: int64

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [35]:
# Random Forest Classifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Make predictions
y_pred = rf.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        62
           1       0.91      0.74      0.82        27
           2       0.77      0.83      0.80        24

    accuracy                           0.89       113
   macro avg       0.87      0.85      0.86       113
weighted avg       0.90      0.89      0.89       113

[[61  0  1]
 [ 2 20  5]
 [ 2  2 20]]


In [36]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust n_neighbors as needed

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.94      0.97      0.95        62
           1       0.95      0.70      0.81        27
           2       0.72      0.88      0.79        24

    accuracy                           0.88       113
   macro avg       0.87      0.85      0.85       113
weighted avg       0.90      0.88      0.88       113

[[60  0  2]
 [ 2 19  6]
 [ 2  1 21]]


In [37]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Initialize SVM Classifier
svm = SVC(kernel='rbf', C=1.0, random_state=42)  # You can change kernel to 'linear', 'poly', etc.

# Train the model
svm.fit(X_train, y_train)

# Make predictions
y_pred = svm.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.59      1.00      0.74        62
           1       0.88      0.26      0.40        27
           2       0.00      0.00      0.00        24

    accuracy                           0.61       113
   macro avg       0.49      0.42      0.38       113
weighted avg       0.53      0.61      0.50       113

[[62  0  0]
 [20  7  0]
 [23  1  0]]


C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize Decision Tree Classifier
dt = DecisionTreeClassifier(criterion='gini', splitter='best', random_state=42)  
# You can change criterion to 'entropy' and splitter to 'random' if needed

# Train the model
dt.fit(X_train, y_train)

# Make predictions
y_pred = dt.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.91      0.98      0.95        62
           1       0.90      0.70      0.79        27
           2       0.80      0.83      0.82        24

    accuracy                           0.88       113
   macro avg       0.87      0.84      0.85       113
weighted avg       0.89      0.88      0.88       113

[[61  0  1]
 [ 4 19  4]
 [ 2  2 20]]


In [39]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize MLP Classifier (ANN)
ann = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', max_iter=500, random_state=42)  
# You can change hidden_layer_sizes, activation, solver, etc.

# Train the model
ann.fit(X_train, y_train)

# Make predictions
y_pred = ann.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        62
           1       0.00      0.00      0.00        27
           2       0.23      1.00      0.37        24

    accuracy                           0.21       113
   macro avg       0.08      0.33      0.12       113
weighted avg       0.05      0.21      0.08       113

[[ 0  0 62]
 [ 7  0 20]
 [ 0  0 24]]


C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [43]:
X.columns

Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps', 'Female', 'Male', 'Normal',
       'Obese', 'Overweight', 'Systolic', 'Diastolic'],
      dtype='object')

In [44]:
def predict_disorder(Gender, Age, Occupation, Sleep_Duration, Quality_of_Sleep, 
                     Physical_Activity_Level, Stress_Level, BMI_Category, 
                     Blood_Pressure, Heart_Rate, Daily_Steps):
    b,c = Blood_Pressure.split('/')
    systolic = int(b)
    diastolic = int(c)
    x = np.zeros(14)  
    print(x)
    print(x,b,c)
    
    x[0] = Age
    x[1] = Sleep_Duration
    x[2] = Quality_of_Sleep
    x[3] = Physical_Activity_Level
    x[4] = Stress_Level
    x[5] = Heart_Rate
    x[6] = Daily_Steps
    if(Gender == "Male"):
        x[8] = 1
    else:
        x[7] = 1

    if (BMI_Category == 'Normal'):
        x[9] = 1
    elif (BMI_Category == 'Obese'):
        x[10] = 1
    else:
        x[11] = 1

    x[12] = b
    x[13] = c


    return rf.predict([x])[0]

In [47]:
predict_disorder('Female',	29,	'Nurse',	6.5,	5,	40,	7,	'Normal Weight',	'132/87',	80,	4000)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 132 87


C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


2

In [48]:
import pickle
with open('Sleep_Disorder.pickle','wb') as f:
    pickle.dump(rf,f)